### ISSUE TITLE
Crafting Recipes

### ISSUE THREAD

**Issue by Fortist** [KryptonCaptain/SimpleConveyors#1]
????
Could make my own I guess.

**Comment by KryptonCaptain** [comment]
As in, what are the recipes? They're all basically the same as the IE recipes, except I switched out treated wood for normal wood on the sorter

Converyor:
-3 leather
-iron, redstone, iron

Dropper one is:
-conveyor
-hopper
-conveyor

Sorter:
-iron, redstone, iron
-plank, chest, plank
-iron, redstone, iron

Hammer:
-blank, iron, string
-blank, stick, iron
-stick

https://github.com/KryptonCaptain/SimpleConveyors/blob/master/src/main/java/blusunrize/conveyors/common/IERecipes.java

**Comment by Fortist** [comment]
I ment there were no recipes for the blocks. At least when I last checked.

**Comment by KryptonCaptain** [comment]
Yep. You're right - I totally missed it. The recipes class and shit exist, but the ONE LINE that calls them for registry was fucking missing.

**Comment by KryptonCaptain** [comment]
Officially fixed in 1.02 release
